services:
  aplicacion:
    build: .
    container_name: app_subastas
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PUERTO=3000
      - NODE_ENV=desarrollo
    volumes:
      - .:/app
      - /app/node_modules
